name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [x86_64-linux]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: attic login
        run: attic login chutney http://13.202.152.28 ${{ secrets.ATTIC_LOGIN_TOKEN }}
      - name: om show
        run: om show .
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}" --include-all-dependencies
      - name: attic push
        run: attic push chutney:oss result
