name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ x86_64-linux, aarch64-linux ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: attic login
        run: attic login chutney https://cache.nixos.asia ${{ secrets.ATTIC_LOGIN_TOKEN }}
      - name: om show
        run: om show .
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}"
      - name: attic push
        run: attic push chutney:oss result
