let
  shivaraj = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN5Ov2zDIG59/DaYKjT0sMWIY15er1DZCT9SIak07vK";
  srid = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQRxPoqlThDrkR58pKnJgmeWPY9/wleReRbZ2MOZRyd";
  admins = [ shivaraj srid ];

  # Will change if the VPS is up/downgraded.
  # In such a case, get the new public host key using `ssh-keyscan <host-address>` before deploying.
  #
  # TODO: Document this
  chutney = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIABXotJBFPrGcHuS9yKMUTMSJl+MCn2yISkaYs5B2gw0";
in
{
  # Generated using https://docs.attic.rs/admin-guide/deployment/nixos.html#generating-the-credentials-file
  "attic/env.age".publicKeys = admins ++ [ chutney ];
  # Generated by running on `chutney`: `atticd-atticadm make-token --sub 'e2e-root' --validity '2y' --push '*' --pull '*' --delete '*' --create-cache '*' --destroy-cache '*' --configure-cache '*' --configure-cache-retention '*'`
  "attic/root-token.age".publicKeys = admins;
  # Assumes the cache is created by running: `nix run nixpkgs#attic-client cache create oss`
  # Although not a necessity to create the token below, the cache is also made public by running: `nix run nixpkgs#attic-client -- cache configure oss --public`
  # Generated by running on `chutney`: `atticd-atticadm make-token --sub oss-push --validity '2y' --pull oss --push oss`
  "attic/oss-push-token.age".publicKeys = admins;
}
